import RainbowKitAndWagmiProvider from "./RainbowKitAndWagmiProvider";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import Layout from "@/components/shared/Layout";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ClerkProvider>
          <RainbowKitAndWagmiProvider>
            <Layout>{children}</Layout>
          </RainbowKitAndWagmiProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
